version: "3.4"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8080"

  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    volumes:
      - pg:/var/lib/postgresql/data


volumes:
  pg: